#include "TFGLevelTwoDirector.h"
#include "GameFramework/PlayerController.h"
#include "Kismet/GameplayStatics.h"
#include "TFGCharacterBase.h"
#include "TFGObjectiveWidget.h"
#include "TFGQuestComponent.h"
ATFGLevelTwoDirector::ATFGLevelTwoDirector(){PrimaryActorTick.bCanEverTick=false;} void ATFGLevelTwoDirector::BeginPlay(){Super::BeginPlay();InitializeMission();}
void ATFGLevelTwoDirector::InitializeMission(){ATFGCharacterBase* C=Cast<ATFGCharacterBase>(UGameplayStatics::GetPlayerCharacter(this,0));if(!C||!C->GetQuestComponent())return;PlayerCharacter=C;QuestComponent=C->GetQuestComponent();QuestComponent->OnQuestChanged.AddDynamic(this,&ATFGLevelTwoDirector::HandleQuestChanged);FTFGQuestState S;if(!QuestComponent->GetQuestState(QuestId,S)){QuestComponent->StartQuest(QuestId);S.QuestId=QuestId;S.Stage=0;S.bCompleted=false;}if(APlayerController* PC=UGameplayStatics::GetPlayerController(this,0)){ObjectiveWidget=CreateWidget<UTFGObjectiveWidget>(PC,UTFGObjectiveWidget::StaticClass());if(ObjectiveWidget)ObjectiveWidget->AddToViewport(20);}if(S.bCompleted||S.Stage>=6)FinishMission();else ApplyObjectiveForStage(S.Stage);}
void ATFGLevelTwoDirector::HandleQuestChanged(FName Id,int32 Stage){if(Id!=QuestId)return;FTFGQuestState S;if(UTFGQuestComponent* Q=QuestComponent.Get()){if(Q->GetQuestState(QuestId,S)&&(S.bCompleted||Stage>=6)){FinishMission();return;}}ApplyObjectiveForStage(Stage);}
void ATFGLevelTwoDirector::ApplyObjectiveForStage(int32 Stage){if(!ObjectiveWidget)return;FText O;switch(Stage){case 0:O=FText::FromString(TEXT("Follow the warning bells back toward the festival district."));break;case 1:O=FText::FromString(TEXT("Guide civilians toward the protected sanctuary route."));break;case 2:O=FText::FromString(TEXT("Defeat the first Veyr soldiers inside the city."));break;case 3:O=FText::FromString(TEXT("Reach the southern district and help the trapped families."));break;case 4:O=FText::FromString(TEXT("Break through the Veyr blockade guarding the safe district."));break;case 5:O=FText::FromString(TEXT("Get the survivors through the protected district gate."));break;default:O=FText::FromString(TEXT("The survivors are safe. The palace is under attack."));break;}ObjectiveWidget->SetObjective(FText::FromString(TEXT("LEVEL 2 — THE SKY TURNS RED")),O);ObjectiveWidget->SetObjectiveVisible(true);}
void ATFGLevelTwoDirector::FinishMission(){if(bFinished)return;bFinished=true;if(UTFGQuestComponent* Q=QuestComponent.Get()){FTFGQuestState S;if(Q->GetQuestState(QuestId,S)&&!S.bCompleted)Q->CompleteQuest(QuestId);}if(ObjectiveWidget)ObjectiveWidget->SetObjective(FText::FromString(TEXT("LEVEL 2 COMPLETE")),FText::FromString(TEXT("The palace bells are still ringing. Kael turns toward the royal district.")));}
