#include "TFGLevelTwoPrototypeWorld.h"
#include "Components/InstancedStaticMeshComponent.h"
#include "Components/SceneComponent.h"
#include "Engine/StaticMesh.h"
#include "Engine/World.h"
#include "UObject/ConstructorHelpers.h"
#include "TFGCheckpointActor.h"
#include "TFGEncounterZone.h"
#include "TFGEnemyCharacter.h"
#include "TFGInteractableActor.h"
#include "TFGLevelTransitionActor.h"
#include "TFGVeyrBruteEnemy.h"
ATFGLevelTwoPrototypeWorld::ATFGLevelTwoPrototypeWorld(){PrimaryActorTick.bCanEverTick=false;SceneRoot=CreateDefaultSubobject<USceneComponent>(TEXT("SceneRoot"));SetRootComponent(SceneRoot);Geometry=CreateDefaultSubobject<UInstancedStaticMeshComponent>(TEXT("PrototypeGeometry"));Geometry->SetupAttachment(SceneRoot);Geometry->SetCollisionEnabled(ECollisionEnabled::QueryAndPhysics);Geometry->SetCollisionResponseToAllChannels(ECR_Block);static ConstructorHelpers::FObjectFinder<UStaticMesh> Cube(TEXT("/Engine/BasicShapes/Cube.Cube"));if(Cube.Succeeded())Geometry->SetStaticMesh(Cube.Object);}
void ATFGLevelTwoPrototypeWorld::BeginPlay(){Super::BeginPlay();AddBox(FVector(2100,0,-75),FVector(46,10,.75));AddBox(FVector(2100,1050,250),FVector(46,.5,3.2));AddBox(FVector(2100,-1050,250),FVector(46,.5,3.2));for(int32 I=0;I<9;++I){float X=420+I*455;float C=(I%3==0)?.55f:1.f;AddBox(FVector(X,660,150*C),FVector(1.8,2.2,3*C));AddBox(FVector(X+170,-660,130*C),FVector(1.6,2,2.6*C));}AddBox(FVector(3050,0,120),FVector(5,.7,2.4));AddBox(FVector(4050,-260,210),FVector(1,1,4.2));AddBox(FVector(4050,260,210),FVector(1,1,4.2));AddBox(FVector(4050,0,430),FVector(1,4,.7));SpawnCheckpoint(FVector(180,0,90),TEXT("L02_Start"));SpawnInteraction(FVector(520,0,80),FText::FromString(TEXT("Follow the warning bells")),TEXT("WarningBells"),0,1,FText::FromString(TEXT("Kael")),FText::FromString(TEXT("Those are not festival bells. The northern alarm is sounding.")));SpawnInteraction(FVector(1100,80,80),FText::FromString(TEXT("Guide the civilians toward sanctuary")),TEXT("EvacuateCivilians"),1,2,FText::FromString(TEXT("Elaris Citizen")),FText::FromString(TEXT("The market road is blocked. Please—show us another way.")));SpawnEncounter(FVector(1650,0,40),2,3,3,false);SpawnCheckpoint(FVector(2150,0,90),TEXT("L02_AfterFirstAttack"));SpawnInteraction(FVector(2600,-80,80),FText::FromString(TEXT("Free the trapped families")),TEXT("SouthernDistrictFamilies"),3,4,FText::FromString(TEXT("Kael")),FText::FromString(TEXT("The street has collapsed, but the alley to the sanctuary is still open.")));SpawnEncounter(FVector(3200,0,40),4,5,3,true);SpawnCheckpoint(FVector(3650,0,90),TEXT("L02_BlockadeCleared"));FActorSpawnParameters P;P.SpawnCollisionHandlingOverride=ESpawnActorCollisionHandlingMethod::AlwaysSpawn;if(ATFGLevelTransitionActor* E=GetWorld()->SpawnActor<ATFGLevelTransitionActor>(ATFGLevelTransitionActor::StaticClass(),FVector(4050,0,100),FRotator::ZeroRotator,P)){E->InteractionId=TEXT("ProtectedDistrictGate");E->InteractionPrompt=FText::FromString(TEXT("Secure the protected district"));E->QuestId=QuestId;E->RequiredQuestStage=5;E->AdvanceQuestToStage=6;E->bCompleteQuest=true;E->bOneShot=true;E->LevelToComplete=2;E->SpeakerName=FText::FromString(TEXT("Captain Arlen"));E->StoryLine=FText::FromString(TEXT("The civilians are inside. The palace is under siege—go. We hold this district."));E->RefreshPresentation();}}
void ATFGLevelTwoPrototypeWorld::AddBox(const FVector&L,const FVector&S,const FRotator&R){if(Geometry)Geometry->AddInstance(FTransform(R,L,S));}ATFGInteractableActor* ATFGLevelTwoPrototypeWorld::SpawnInteraction(const FVector&L,const FText&Pm,FName Id,int32 Req,int32 Adv,const FText&Sp,const FText&Line){if(!GetWorld())return nullptr;FActorSpawnParameters P;P.SpawnCollisionHandlingOverride=ESpawnActorCollisionHandlingMethod::AdjustIfPossibleButAlwaysSpawn;auto*A=GetWorld()->SpawnActor<ATFGInteractableActor>(ATFGInteractableActor::StaticClass(),L,FRotator::ZeroRotator,P);if(A){A->InteractionPrompt=Pm;A->InteractionId=Id;A->QuestId=QuestId;A->RequiredQuestStage=Req;A->AdvanceQuestToStage=Adv;A->bOneShot=true;A->SpeakerName=Sp;A->StoryLine=Line;A->RefreshPresentation();}return A;}ATFGEncounterZone* ATFGLevelTwoPrototypeWorld::SpawnEncounter(const FVector&L,int32 Req,int32 Adv,int32 Count,bool Brute){if(!GetWorld())return nullptr;FActorSpawnParameters P;P.SpawnCollisionHandlingOverride=ESpawnActorCollisionHandlingMethod::AlwaysSpawn;auto*E=GetWorld()->SpawnActor<ATFGEncounterZone>(ATFGEncounterZone::StaticClass(),L,FRotator::ZeroRotator,P);if(E){E->QuestId=QuestId;E->RequiredQuestStage=Req;E->AdvanceQuestToStage=Adv;int32 N=Brute?FMath::Max(0,Count-1):Count;for(int32 I=0;I<N;++I)E->EnemyClasses.Add(ATFGEnemyCharacter::StaticClass());if(Brute)E->EnemyClasses.Add(ATFGVeyrBruteEnemy::StaticClass());}return E;}void ATFGLevelTwoPrototypeWorld::SpawnCheckpoint(const FVector&L,FName Id){FActorSpawnParameters P;P.SpawnCollisionHandlingOverride=ESpawnActorCollisionHandlingMethod::AlwaysSpawn;if(auto*C=GetWorld()->SpawnActor<ATFGCheckpointActor>(ATFGCheckpointActor::StaticClass(),L,FRotator::ZeroRotator,P))C->ConfigureCheckpoint(Id,TEXT("L02_TheSkyTurnsRed"),true);}
